tasks:
  - name: chines
    type: standard
    dataset:
      name: ChineseSimpleQA
      params:
        data_path: E:/eval/Chinese-SimpleQA/chinese_simpleqa.jsonl
    prompt:
      type: qa
    model:
      name: MiniMax
    evaluators:
      - name: accuracy