tasks:
  - name: hle
    type: standard
    dataset:
      name: HLE
      params:
        data_path: "data/hle/test.jsonl"
        limits: 20
    prompt_builder:
      name: qa_builder
    model:
      name: MiniMax
      params:
        generation_config:
          temperature: 0.0
          max_tokens: 1024
    evaluators:
      - name: amo_boxed
    output_path: results/hle
