tasks:
  - name: humaneval
    type: standard
    dataset:
      name: HumanEval
      params:
        data_path: "data/humaneval/test.jsonl"
        limits: 20
    prompt_builder:
      name: qa_builder
    model:
      name: MiniMax
      params:
        generation_config:
          temperature: 0.0
          max_tokens: 1024
    evaluators:
      - name: humaneval_pass
    output_path: results/humaneval
